# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  test:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@28-fix-supported-range-checks
    with:
      #Grunt fails due to CSS styling needing an !important.
      disable_grunt: true